---
- name: Repository Sets | Reset accumulated results
  ansible.builtin.set_fact:
    __rs_info_list: []

- name: Repository Sets | Get Organizations
  ansible.builtin.include_tasks: resolve_export_organizations.yaml
  vars:
    __export_org_call_type: Repository Sets

- name: Repository Sets | Set organization list
  ansible.builtin.set_fact:
    info_list: >-
      {{
        __result_organizations.organizations
        | infra.satellite_configuration.satellite_configuration_filter_export_organizations(
            satellite_configuration_filetree_create_filters
          )
        | sort(attribute='id')
      }}

- name: Repository Sets | Get Syn Plans Info
  ansible.builtin.include_tasks: get_repository_sets_do_work.yaml
  loop: "{{ info_list }}"
  loop_control:
    loop_var: __current_org

- name: Repository Sets | Template Out Results
  when:
    - __rs_info_list is defined
    - __rs_info_list | length > 0
  ansible.builtin.include_tasks: template_out.yaml
  vars:
    template_type: satellite_repository_sets
    info_list: "{{ __rs_info_list | default([]) }}"
...
