---
- name: Content Views | Reset the results variable
  ansible.builtin.set_fact:
    result_api_response: {}
    __rs_info_list: []

- name: Content Views | Get Content Views
  ansible.builtin.include_tasks: api_call.yaml
  vars:
    call_type: Content Views
    api_link: >-
      {{
        '/katello/api/content_views?full_result=true'
        | infra.satellite_configuration.satellite_configuration_append_export_search_for_resource(
            satellite_configuration_filetree_create_filters,
            'content_views'
          )
      }}

- name: Content Views | Retain the Content Views' info
  ansible.builtin.set_fact:
    __content_views_list: >-
      {{
        result_api_response.json.results
        | infra.satellite_configuration.satellite_configuration_filter_export_items(
            satellite_configuration_filetree_create_filters
            | infra.satellite_configuration.satellite_configuration_filters_for_post_api_export(
                'content_views'
              )
          )
      }}

- name: Content Views | Show debug information (__content_views_list)
  ansible.builtin.debug:
    var: __content_views_list
    verbosity: 1

- name: Content Views | Get Content View filters Info
  ansible.builtin.include_tasks: get_content_view_filters.yaml
  loop: "{{ __content_views_list }}"
  loop_control:
    loop_var: __current_content_view

- name: Content Views | Template Out Results
  when:
    - __rs_info_list is defined
    - __rs_info_list | length > 0
  ansible.builtin.include_tasks: template_out.yaml
  vars:
    template_type: satellite_content_views
    info_list: "{{ __rs_info_list | default([]) }}"
...
