---
- name: Lifecycle Environments | Reset the results variable
  ansible.builtin.set_fact:
    result_api_response: {}

- name: Lifecycle Environments | Get Info
  ansible.builtin.include_tasks: api_call.yaml
  vars:
    call_type: Lifecycle Environments
    api_link: >-
      {{
        '/katello/api/environments?full_result=true'
        | infra.satellite_configuration.satellite_configuration_append_export_search_for_resource(
            satellite_configuration_filetree_create_filters,
            'lifecycle_environments'
          )
      }}

- name: Lifecycle Environments | Set Info List
  ansible.builtin.set_fact:
    info_list: >-
      {{
        result_api_response.json.results
        | rejectattr('name', '==', 'Library')
        | infra.satellite_configuration.satellite_configuration_filter_export_items(
            satellite_configuration_filetree_create_filters
            | infra.satellite_configuration.satellite_configuration_filters_for_post_api_export(
                'lifecycle_environments'
              )
          )
        | sort(attribute='id')
      }}

- name: Lifecycle Environments | Template Out Results
  when:
    - info_list is defined
    - info_list | length > 0
  ansible.builtin.include_tasks: template_out.yaml
  vars:
    template_type: satellite_lifecycle_environments
...
