---
- name: Content Credentials | Reset the results variable
  ansible.builtin.set_fact:
    result_api_response: {}

- name: Content Credentials | Get Organizations
  ansible.builtin.include_tasks: resolve_export_organizations.yaml
  vars:
    __export_org_call_type: Content Credentials

- name: Content Credentials | Get Info
  ansible.builtin.include_tasks: api_call.yaml
  vars:
    call_type: Content Credentials
    api_link: >-
      {{
        (
          '/katello/api/content_credentials?organization_id=' ~ (__current_org.id | string)
          ~ '&full_result=true'
        )
        | infra.satellite_configuration.satellite_configuration_append_export_search_for_resource(
            satellite_configuration_filetree_create_filters,
            'content_credentials'
          )
      }}
  loop: >-
    {{
      __result_organizations.organizations
      | infra.satellite_configuration.satellite_configuration_filter_export_organizations(
          satellite_configuration_filetree_create_filters
        )
    }}
  loop_control:
    loop_var: __current_org
  register: result_api_response

- name: Content Credentials | Set Info List
  ansible.builtin.set_fact:
    info_list: >-
      {{
        result_api_response.json.results
        | infra.satellite_configuration.satellite_configuration_filter_export_items(
            satellite_configuration_filetree_create_filters
            | infra.satellite_configuration.satellite_configuration_filters_for_post_api_export(
                'content_credentials'
              )
          )
        | sort(attribute='id')
      }}

- name: Content Credentials | Template Out Results
  when:
    - info_list is defined
    - info_list | length > 0
  ansible.builtin.include_tasks: template_out.yaml
  vars:
    template_type: satellite_content_credentials
...
