---
- name: Usergroups | Reset the results variable
  ansible.builtin.set_fact:
    result_api_response: {}

- name: Usergroups | Get Usergroups
  ansible.builtin.include_tasks: api_call.yaml
  vars:
    call_type: Usergroups
    api_link: "/api/usergroups?per_page=all"

- name: Usergroups | Retain the Usergroups' info
  ansible.builtin.set_fact:
    __usergroups_list: >-
      {{
        result_api_response.json.results
        | infra.satellite_configuration.satellite_configuration_filter_export_items(
            satellite_configuration_filetree_create_filters
          )
      }}

- name: Usergroups | Get External Usergroups Info
  ansible.builtin.include_tasks: get_usergroups_do_work.yaml
  loop: "{{ __usergroups_list }}"
  loop_control:
    loop_var: __current_usergroup

- name: Usergroups | Template Out Results
  when:
    - __rs_info_list is defined
    - __rs_info_list | length > 0
  ansible.builtin.include_tasks: template_out.yaml
  vars:
    template_type: satellite_usergroups
    info_list: "{{ __rs_info_list | default([]) }}"
...
