---
- name: Installation Medium (Do Work) | Reset the results variable
  ansible.builtin.set_fact:
    result_api_response: {}

- name: Installation Medium (Do Work) | Get Installation Medium
  ansible.builtin.include_tasks: api_call.yaml
  vars:
    call_type: Installation Medium (Do Work)
    api_link: "/api/media/{{ __current_installation_medium.id }}/"

- name: Installation Medium (Do Work) | Block to do the job when there's a job to do
  when:
    - result_api_response.content is defined
    - result_api_response.content | length > 0
  block:
    - name: Installation Medium (Do Work) | Retain installation medium detail
      ansible.builtin.set_fact:
        __installation_medium_detail: "{{ result_api_response.content | from_json }}"

    - name: Installation Medium (Do Work) | Enrich operatingsystem refs
      ansible.builtin.include_tasks: enrich_operatingsystem_refs.yaml
      vars:
        __enrich_os_refs_source: "{{ __installation_medium_detail.operatingsystems | default([]) }}"
      when: __installation_medium_detail.operatingsystems | default([]) | length > 0

    - name: Installation Medium (Do Work) | Set Info List (can take a while...)
      when:
        - not (
            (__filetree_create_effective_skip_locked_installation_mediums | default(true) | bool)
            and (__installation_medium_detail.locked | default(false) | bool)
          )
      ansible.builtin.set_fact:
        __rs_info_list: >-
          {{
            __rs_info_list
            + [
                __installation_medium_detail
                | combine({'operatingsystems': __enrich_os_refs_result | default([])}, recursive=True)
                if (__installation_medium_detail.operatingsystems | default([]) | length > 0)
                else __installation_medium_detail
              ]
          }}

...
