---
- name: Partition Table (Do Work) | Reset the results variable
  ansible.builtin.set_fact:
    result_api_response: {}

- name: Partition Table (Do Work) | Get Partition Table
  ansible.builtin.include_tasks: api_call.yaml
  vars:
    call_type: Partition Table (Do Work)
    api_link: "/api/ptables/{{ __current_partition_table.id }}/"

- name: Partition Table (Do Work) | Block to do the job when there's a job to do
  when:
    - result_api_response.content is defined
    - result_api_response.content | length > 0
  block:
    - name: Partition Table (Do Work) | Set Info List (can take a while...)
      when:
        - not (
            (__filetree_create_effective_skip_locked_partition_tables | default(true) | bool)
            and ((result_api_response.content | from_json).locked | default(false) | bool)
          )
      ansible.builtin.set_fact:
        __rs_info_list: "{{ __rs_info_list + [result_api_response.content | from_json] }}"
...
