---
- name: Provisioning Template (Do Work) | Reset the results variable
  ansible.builtin.set_fact:
    result_api_response: {}

- name: Provisioning Template (Do Work) | Get Provisioning Template
  ansible.builtin.include_tasks: api_call.yaml
  vars:
    call_type: Provisioning Template (Do Work)
    api_link: "/api/provisioning_templates/{{ __current_provisioning_template.id }}/"

- name: Provisioning Template (Do Work) | Block to do the job when there's a job to do
  when:
    - result_api_response.content is defined
    - result_api_response.content | length > 0
  block:
    - name: Provisioning Template (Do Work) | Retain provisioning template detail
      ansible.builtin.set_fact:
        __provisioning_template_detail: "{{ result_api_response.content | from_json }}"

    - name: Provisioning Template (Do Work) | Enrich operatingsystem refs
      ansible.builtin.include_tasks: enrich_operatingsystem_refs.yaml
      vars:
        __enrich_os_refs_source: "{{ __provisioning_template_detail.operatingsystems | default([]) }}"
      when: __provisioning_template_detail.operatingsystems | default([]) | length > 0

    - name: Provisioning Template (Do Work) | Set Info List (can take a while...)
      when:
        - not (
            (__filetree_create_effective_skip_locked_provisioning_templates | default(true) | bool)
            and (__provisioning_template_detail.locked | default(false) | bool)
          )
      ansible.builtin.set_fact:
        __rs_info_list: >-
          {{
            __rs_info_list
            + [
                __provisioning_template_detail
                | combine({'operatingsystems': __enrich_os_refs_result | default([])}, recursive=True)
                if (__provisioning_template_detail.operatingsystems | default([]) | length > 0)
                else __provisioning_template_detail
              ]
          }}

...
