---
- name: Sync Plans | Reset the results variable
  ansible.builtin.set_fact:
    result_api_response: {}

- name: Sync Plans | Get Organizations
  ansible.builtin.include_tasks: get_organizations.yaml

- name: Sync Plans | Get Syn Plans Info
  ansible.builtin.include_tasks: get_sync_plans_do_work.yaml
  loop: "{{ info_list }}"
  loop_control:
    loop_var: __current_org

- name: Sync Plans | Template Out Results
  when:
    - __sp_info_list is defined
    - __sp_info_list | length > 0
  ansible.builtin.include_tasks: template_out.yaml
  vars:
    template_type: satellite_sync_plans
    info_list: >-
      {{
        __sp_info_list
        | infra.satellite_configuration.satellite_configuration_filter_export_items(
            satellite_configuration_filetree_create_filters
            | infra.satellite_configuration.satellite_configuration_filters_for_post_api_export(
                'sync_plans'
              )
          )
      }}
...
